name: vault-credhub-proxy

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

releases:
- name: vault-credhub-proxy
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

instance_groups:
- name: vault-credhub-proxy
  instances: 1
  azs: [z1]
  vm_type: small
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: vault-credhub-proxy
    release: vault-credhub-proxy
    properties:
      tls:
        certificate: ((vault_credhub_proxy_ssl.certificate))((vault_credhub_proxy_ssl.ca))
        private_key: ((vault_credhub_proxy_ssl.private_key))
      credhub:
        server: (( grab $CREDHUB_URL ))
        ca: (( grab $CREDHUB_CA_CERT ))

variables:
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: Default CA
- name: vault_credhub_proxy_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: vault-credhub-proxy.default.vault-credhub-proxy.bosh
    alternative_names:
    - 127.0.0.1
