name: vault-credhub-proxy

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000


stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

instance_groups:
- name: vault-credhub-proxy
  instances: 1
  azs: [z1]
  vm_type: small
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: bpm
    release: bpm
  - name: vault-credhub-proxy
    release: vault-credhub-proxy
    properties:
      address: 0.0.0.0:8200
      tls:
        certificate: ((vault_credhub_proxy_ssl.certificate))((vault_credhub_proxy_ssl.ca))
        private_key: ((vault_credhub_proxy_ssl.private_key))
      credhub:
        server: (( grab $CREDHUB_URL ))
        ca: (( grab $CREDHUB_CA_CERT ))

variables:
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: Default CA
- name: vault_credhub_proxy_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: vault-credhub-proxy.default.vault-credhub-proxy.bosh
    alternative_names:
    - 127.0.0.1

# releases section must come last due to manipulation by the pipeline
releases:
- name: vault-credhub-proxy
  sha1: df2656c392e7fbaa4ba25c9149c942ff7cce859e
  url: https://github.com/cloudfoundry-community/vault-credhub-proxy-boshrelease/releases/download/v1.2.0/vault-credhub-proxy-1.2.0.tgz
  version: 1.2.0
- name: bpm
  sha1: ad12bb4e1d2c0b94ef679670a99adaff920850d0
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.2.3
  version: 1.2.3
