name: vault-credhub-proxy

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

releases:
- name: vault-credhub-proxy
  sha1: df2656c392e7fbaa4ba25c9149c942ff7cce859e
  url: https://github.com/cloudfoundry-community/vault-credhub-proxy-boshrelease/releases/download/v1.2.0/vault-credhub-proxy-1.2.0.tgz
  version: 1.2.0
- name: bpm
  sha1: ad12bb4e1d2c0b94ef679670a99adaff920850d0
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.2.3
  version: 1.2.3
